# extractor constants
DEFAULT_CHUNK_SIZE = 1024 * 10
DEFAULT_CHUNKS_LIMIT = 1000
DEFAULT_DOWNLOAD_THRESHHOLD = 1024 * 1000 * 1.5
DEFAULT_STSC_SIZE_THRESHOLD = 1024 * 1000

# verbose levels
READING_VERBOSE = 100
BOX_FINDERS_VERBOSE = 10
ALG_VARS_VERBOSE = 5
SUMMERY_VERBOSE = 1

# tuples indexes
BOX_SIZE_IDX = 0
BOX_OFFSET_IDX = 1

CHUNK_NUMBER_IDX = 0
CHUNK_FIRST_SAMPLE_IDX = 1
CHUNK_DESCRIPTION_DATA_IDX = 2

SAMPLE_NUMBER_IDX = 0
SAMPLE_OFFSET_IN_CHUNK_IDX = 1
SAMPLE_OFFSET_IN_FILE_IDX = 1
SAMPLE_SIZE_IDX = 2

# extractor status codes
SUCCESS_CODE = 10
STSC_LIMIT_FAIL_CODE = 11
BOX_NOT_FOUND_FAIL_CODE = 12
DOWNLOAD_LIMIT_FAIL_CODE = 13
CHUNKS_LIMIT_FAIL_CODE = 14
PACKETS_READER_FAIL_CODE = 15
SAMPLE_DESCRIPTION_DATA_NOT_FOUND_FAIL_CODE = 16
SAMPLE_CONVERT_ERROR_FAIL_CODE = 17
VIDEO_TRACK_NOT_FOUND_FAIL_CODE = 18
CODEC_NOT_SUPPORTED_FAIL_CODE = 19
UNKNOWN_ERROR_FAIL_CODE = 20
